### ISSUE TITLE
Doubt regarding the dealiasing technique

### ISSUE THREAD

**Issue by rickyspaceguy** [LHEEA/HOS-NWT#15]
This is with regards to `resol_HOS.f90`, subroutines `solveHOS` and `solveHOS2`, lines 178-191 and lines 534-547, respectively. They read as 
`!
phix_add = space_2_Fourier(phix_add,'cos','cos')
phiy_add = space_2_Fourier(phiy_add,'cos','cos')
phiz_add = space_2_Fourier(phiz_add,'cos','cos')
!
phix_add_ext = extend(phix_add)
phiy_add_ext = extend(phiy_add)
phiz_add_ext = extend(phiz_add)
!
phix_add = Fourier_2_space(phix_add,'cos','cos')
phiy_add = Fourier_2_space(phiy_add,'cos','cos')
phiz_add = Fourier_2_space(phiz_add,'cos','cos')
phix_add_ext = Fourier_2_space_big(phix_add_ext,'cos','cos')
phiy_add_ext = Fourier_2_space_big(phiy_add_ext,'cos','cos')
phiz_add_ext = Fourier_2_space_big(phiz_add_ext,'cos','cos')
!
`
Why are all FFT and their inverses cos-cos type? Is it inconsequential since phix_add & others are reproduced back by same technique? Is it related to the `extend` subroutine or will this change if instead of cos-cos type, sin-sin type or sin-cos type is implemented?

Moreover when reducing back from extended space to physical space, why is `reduce` not used, instead `filter_ext` is used?

**Comment by gducrozet** [comment]
@rickyspaceguy 
This is a relevant question. The choice is somewhat arbitrary since the additional potential at the free surface is actually evolving as cosh(k(Lx-x)) which is neither a sin nor a cosine function of x.
It is consequently expected that the decomposition of this additional potential on such basis is converging with respect to the number of points and that the dealiasing technique adopted is correct in the removal of aliasing errors in the products appearing in the free surface boundary conditions. Then, you for sure have to use the same eigenfunctions for both Fourier and inverse fourier to get correct results.

With respect to the use of `reduce`, it is actually not transforming back to physical space the quantity of interest, it only works in the modal space. 

Best regards,

Guillaume
