### ISSUE TITLE
forrtl: severe (174): SIGSEGV, segmentation fault occurred

### ISSUE THREAD

**Issue by Bduz** [LHEEA/HOS-NWT#2]
Hello,
I recently started a project at the Maritime Research Institute in the Netherlands (MARIN). In this project, I will take a look at a number of NWTs and possibly recommend one for further use at MARIN.
One of the codes I am considering is HOS-NWT. Thank you for making it available to everyone.
## I compiled both HOS-NWT1.0 and HOS-ocean1.1 with ifort. The latter is working fine but when I start a simulation with the former, I get the following error message:

Wave first order
 At first order
required x-pic mode   19 enabled 512
required y-pic mode    0 enabled   1
 At second order
required x-pic mode   79 enabled 512
required y-pic mode    0 enabled   1
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source  
HOS-NWT            0000000000752CDD  Unknown               Unknown  Unknown
HOS-NWT            0000000000632BAA  fourier_fftw_mp_e         485  fourier_FFTW.f90
HOS-NWT            00000000006312F9  fourier_fftw_mp_d         442  fourier_FFTW.f90
HOS-NWT            0000000000566F56  initial_condition         396  initial_condition.f90
HOS-NWT            00000000004168AB  MAIN__                    408  HOS-NWT.f90
HOS-NWT            0000000000404FAC  Unknown               Unknown  Unknown
libc.so.6          0000003FAF41ED5D  Unknown               Unknown  Unknown
## HOS-NWT            0000000000404EA9  Unknown               Unknown  Unknown

Do you have any ideas for me so that I can resolve this issue?

All the Best,
Bulent

**Comment by gducrozet** [comment]
Hello,

In order to understand the problem, could you specify which problem you try to solve (i.e. i_case)? Such error may appear if an input and/or output files is not accessible. This is, in my opinion, the first thing to check.

Furthermore, did you try to run the different benchmarks available in Benchmark directory, to test if your installation is correct?

Best regards,

Guillaume.

**Comment by Bduz** [comment]
I am trying to run a simulation using the input file that exists in HOS-NWT-1.0\bin directory. icase=2
I tried to run benchmark cases as well, I got the same error message.

**Comment by gducrozet** [comment]
Hi,
Unfortunately, I have not experienced such error... 
If HOS-ocean is working fine, I assume you have the correct libraries linked within the code. Few ideas : 
- since you are using ifort, you added the USE statement recommended : USE IFPORT, only:RAND in initial_condition.f90?
- Did you try to compile the program with debugging options? i.e. use 'make Debug -B' (latter -B option is to ensure that all source files are recompiled). You can also try to do a 'make clean' to clean all auxiliary files
- which version of ifort are you using? I have tested with version 13.1.1

Best regards,
Guillaume

**Comment by Bduz** [comment]
I tried the first two, but unfortunately it didnot help. I am using ifort 13.1.1
I ran the program in debugger, and it seems like the following lines in fourier_FFTW.f90 are causing the problem:

! Local variables
type(C_PTR)      :: plan
!
plan = select_plan_add(CS_z, CS_y, FB)
!
IF ((n2 /= 1) .AND. (CS_y == 'sin')) THEN
   in_add(:,1)  = 0.0_rp
   in_add(:,n2) = 0.0_rp
END IF
!
CALL dfftw_execute_(plan)

I think the pointer "plan" is pointing somewhere that the function does not find. Is there some exchange of information happening here between C and Fortran?

**Comment by gducrozet** [comment]
Hello,

This error seems strange to me since you are using a configuration on which I have tested the code... Which operating system are using?
By the way, you could try the following process:
- Re-compile the external libraries, ensuring you are using the correct version (cf. wiki)
- check that file fftw.f03 generated with your compiler and OS during compilation of fftw3.3.4 is the same than the one used in HOS-NWT (defines some constants)
- Make a git clone from github repository
- Make the slight changes necessary to compile with ifort (Makefile + initial_condition.f90 : cf wiki)
- Re-compile all the code: 'make all'
- Try to execute one of the benchmark

Regards,
Guillaume
