### ISSUE TITLE
Some confusion of wavemaker in HOS-NWT

### ISSUE THREAD

**Issue by zuiwohuaqian** [LHEEA/HOS-NWT#28]
Hello,
I have some confusions of the wavemaker in HOS-NWT, I got the motion of wavemaker from experiment, but after I multiple the TF function and got the wave component, the calculation broke. Is that matter that the wave is a shallow water wave (with wave length 6m and wave depth 2.8m)? And should I take care about the interval of frequencies in the input of wavemaker?
Thanks a lot.
huaqian.

**Comment by gducrozet** [comment]
Hello @zuiwohuaqian 

Wave length of 6m and water depth of 2.8m is not very shallow water depth and consequently this should not be the issue.
You can make a quick test decreasing the amplitude of your signal (keeping same frequencies) to see if it is easier to compute.

Then, what you need to take care :
- the steepness of the ave you generate. If it is very steep, the computation may break (possible test for this is what I suggested above)
- the discretization you choose. Since HOS-NWT does not filter anything, a too refined discretization can induce unstable features (possible solution for this: try a simulation with M=1 that does not experience stability issues associated to fine grids). The relevant choice is usually to take k_max = 15-25 k_p (with k_max the largest wavenumber solved and k_p the peak wave number)
- the HOS nonlinear order: usually not necessary to go above M=3 or 5
- absorbing beach should efficiently absorb the waves
- Time tolerance correctly chosen

Hope this helps,
Best,

Guillaume

**Comment by zuiwohuaqian** [comment]
thanks for the reply, it really helps!
